// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.dao.AccountDAO;
import com.capgemini.pmo.entity.AccountDataOnDemand;
import com.capgemini.pmo.entity.AccountIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AccountIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AccountIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AccountIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AccountIntegrationTest: @Transactional;
    
    @Autowired
    AccountDataOnDemand AccountIntegrationTest.dod;
    
    @Autowired
    AccountDAO AccountIntegrationTest.accountDAO;
    
    @Test
    public void AccountIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", dod.getRandomAccount());
        long count = accountDAO.count();
        Assert.assertTrue("Counter for 'Account' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AccountIntegrationTest.testFind() {
        Account obj = dod.getRandomAccount();
        Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Account' failed to provide an identifier", id);
        obj = accountDAO.findOne(id);
        Assert.assertNotNull("Find method for 'Account' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Account' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AccountIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", dod.getRandomAccount());
        long count = accountDAO.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Account', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Account> result = accountDAO.findAll();
        Assert.assertNotNull("Find all method for 'Account' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Account' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AccountIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", dod.getRandomAccount());
        long count = accountDAO.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Account> result = accountDAO.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Account' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Account' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AccountIntegrationTest.testFlush() {
        Account obj = dod.getRandomAccount();
        Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Account' failed to provide an identifier", id);
        obj = accountDAO.findOne(id);
        Assert.assertNotNull("Find method for 'Account' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAccount(obj);
        Integer currentVersion = obj.getVersion();
        accountDAO.flush();
        Assert.assertTrue("Version for 'Account' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AccountIntegrationTest.testSaveUpdate() {
        Account obj = dod.getRandomAccount();
        Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Account' failed to provide an identifier", id);
        obj = accountDAO.findOne(id);
        boolean modified =  dod.modifyAccount(obj);
        Integer currentVersion = obj.getVersion();
        Account merged = accountDAO.save(obj);
        accountDAO.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Account' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AccountIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", dod.getRandomAccount());
        Account obj = dod.getNewTransientAccount(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Account' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Account' identifier to be null", obj.getId());
        try {
            accountDAO.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        accountDAO.flush();
        Assert.assertNotNull("Expected 'Account' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AccountIntegrationTest.testDelete() {
        Account obj = dod.getRandomAccount();
        Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Account' failed to provide an identifier", id);
        obj = accountDAO.findOne(id);
        accountDAO.delete(obj);
        accountDAO.flush();
        Assert.assertNull("Failed to remove 'Account' with identifier '" + id + "'", accountDAO.findOne(id));
    }
    
}
