// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.dao.AccountDAO;
import com.capgemini.pmo.entity.Account;
import com.capgemini.pmo.entity.AccountDataOnDemand;
import com.capgemini.pmo.entity.IDP;
import com.capgemini.pmo.entity.IDPDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AccountDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AccountDataOnDemand: @Component;
    
    private Random AccountDataOnDemand.rnd = new SecureRandom();
    
    private List<Account> AccountDataOnDemand.data;
    
    @Autowired
    IDPDataOnDemand AccountDataOnDemand.iDPDataOnDemand;
    
    @Autowired
    AccountDAO AccountDataOnDemand.accountDAO;
    
    public Account AccountDataOnDemand.getNewTransientAccount(int index) {
        Account obj = new Account();
        setAccountexec(obj, index);
        setHeadcount(obj, index);
        setIdp(obj, index);
        setName(obj, index);
        setPmocontact(obj, index);
        return obj;
    }
    
    public void AccountDataOnDemand.setAccountexec(Account obj, int index) {
        String accountexec = "accountexec_" + index;
        if (accountexec.length() > 100) {
            accountexec = accountexec.substring(0, 100);
        }
        obj.setAccountexec(accountexec);
    }
    
    public void AccountDataOnDemand.setHeadcount(Account obj, int index) {
        Integer headcount = new Integer(index);
        obj.setHeadcount(headcount);
    }
    
    public void AccountDataOnDemand.setIdp(Account obj, int index) {
        IDP idp = iDPDataOnDemand.getRandomIDP();
        obj.setIdp(idp);
    }
    
    public void AccountDataOnDemand.setName(Account obj, int index) {
        String name = "name_" + index;
        if (name.length() > 50) {
            name = name.substring(0, 50);
        }
        obj.setName(name);
    }
    
    public void AccountDataOnDemand.setPmocontact(Account obj, int index) {
        String pmocontact = "pmocontact_" + index;
        if (pmocontact.length() > 100) {
            pmocontact = pmocontact.substring(0, 100);
        }
        obj.setPmocontact(pmocontact);
    }
    
    public Account AccountDataOnDemand.getSpecificAccount(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Account obj = data.get(index);
        Long id = obj.getId();
        return accountDAO.findOne(id);
    }
    
    public Account AccountDataOnDemand.getRandomAccount() {
        init();
        Account obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return accountDAO.findOne(id);
    }
    
    public boolean AccountDataOnDemand.modifyAccount(Account obj) {
        return false;
    }
    
    public void AccountDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = accountDAO.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Account' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Account>();
        for (int i = 0; i < 10; i++) {
            Account obj = getNewTransientAccount(i);
            try {
                accountDAO.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            accountDAO.flush();
            data.add(obj);
        }
    }
    
}
