// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.dao.EmployeeRosterDAO;
import com.capgemini.pmo.entity.EmployeeRosterDataOnDemand;
import com.capgemini.pmo.entity.EmployeeRosterIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EmployeeRosterIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EmployeeRosterIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EmployeeRosterIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EmployeeRosterIntegrationTest: @Transactional;
    
    @Autowired
    EmployeeRosterDataOnDemand EmployeeRosterIntegrationTest.dod;
    
    @Autowired
    EmployeeRosterDAO EmployeeRosterIntegrationTest.employeeRosterDAO;
    
    @Test
    public void EmployeeRosterIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'EmployeeRoster' failed to initialize correctly", dod.getRandomEmployeeRoster());
        long count = employeeRosterDAO.count();
        Assert.assertTrue("Counter for 'EmployeeRoster' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EmployeeRosterIntegrationTest.testFind() {
        EmployeeRoster obj = dod.getRandomEmployeeRoster();
        Assert.assertNotNull("Data on demand for 'EmployeeRoster' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EmployeeRoster' failed to provide an identifier", id);
        obj = employeeRosterDAO.findOne(id);
        Assert.assertNotNull("Find method for 'EmployeeRoster' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EmployeeRoster' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EmployeeRosterIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'EmployeeRoster' failed to initialize correctly", dod.getRandomEmployeeRoster());
        long count = employeeRosterDAO.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'EmployeeRoster', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EmployeeRoster> result = employeeRosterDAO.findAll();
        Assert.assertNotNull("Find all method for 'EmployeeRoster' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EmployeeRoster' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EmployeeRosterIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'EmployeeRoster' failed to initialize correctly", dod.getRandomEmployeeRoster());
        long count = employeeRosterDAO.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EmployeeRoster> result = employeeRosterDAO.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'EmployeeRoster' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EmployeeRoster' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EmployeeRosterIntegrationTest.testFlush() {
        EmployeeRoster obj = dod.getRandomEmployeeRoster();
        Assert.assertNotNull("Data on demand for 'EmployeeRoster' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EmployeeRoster' failed to provide an identifier", id);
        obj = employeeRosterDAO.findOne(id);
        Assert.assertNotNull("Find method for 'EmployeeRoster' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEmployeeRoster(obj);
        Integer currentVersion = obj.getVersion();
        employeeRosterDAO.flush();
        Assert.assertTrue("Version for 'EmployeeRoster' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeeRosterIntegrationTest.testSaveUpdate() {
        EmployeeRoster obj = dod.getRandomEmployeeRoster();
        Assert.assertNotNull("Data on demand for 'EmployeeRoster' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EmployeeRoster' failed to provide an identifier", id);
        obj = employeeRosterDAO.findOne(id);
        boolean modified =  dod.modifyEmployeeRoster(obj);
        Integer currentVersion = obj.getVersion();
        EmployeeRoster merged = employeeRosterDAO.save(obj);
        employeeRosterDAO.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EmployeeRoster' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeeRosterIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'EmployeeRoster' failed to initialize correctly", dod.getRandomEmployeeRoster());
        EmployeeRoster obj = dod.getNewTransientEmployeeRoster(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EmployeeRoster' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EmployeeRoster' identifier to be null", obj.getId());
        try {
            employeeRosterDAO.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        employeeRosterDAO.flush();
        Assert.assertNotNull("Expected 'EmployeeRoster' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EmployeeRosterIntegrationTest.testDelete() {
        EmployeeRoster obj = dod.getRandomEmployeeRoster();
        Assert.assertNotNull("Data on demand for 'EmployeeRoster' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EmployeeRoster' failed to provide an identifier", id);
        obj = employeeRosterDAO.findOne(id);
        employeeRosterDAO.delete(obj);
        employeeRosterDAO.flush();
        Assert.assertNull("Failed to remove 'EmployeeRoster' with identifier '" + id + "'", employeeRosterDAO.findOne(id));
    }
    
}
