// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.dao.IDPDAO;
import com.capgemini.pmo.entity.IDPDataOnDemand;
import com.capgemini.pmo.entity.IDPIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect IDPIntegrationTest_Roo_IntegrationTest {
    
    declare @type: IDPIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: IDPIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: IDPIntegrationTest: @Transactional;
    
    @Autowired
    IDPDataOnDemand IDPIntegrationTest.dod;
    
    @Autowired
    IDPDAO IDPIntegrationTest.iDPDAO;
    
    @Test
    public void IDPIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'IDP' failed to initialize correctly", dod.getRandomIDP());
        long count = iDPDAO.count();
        Assert.assertTrue("Counter for 'IDP' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void IDPIntegrationTest.testFind() {
        IDP obj = dod.getRandomIDP();
        Assert.assertNotNull("Data on demand for 'IDP' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IDP' failed to provide an identifier", id);
        obj = iDPDAO.findOne(id);
        Assert.assertNotNull("Find method for 'IDP' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'IDP' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void IDPIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'IDP' failed to initialize correctly", dod.getRandomIDP());
        long count = iDPDAO.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'IDP', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<IDP> result = iDPDAO.findAll();
        Assert.assertNotNull("Find all method for 'IDP' illegally returned null", result);
        Assert.assertTrue("Find all method for 'IDP' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void IDPIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'IDP' failed to initialize correctly", dod.getRandomIDP());
        long count = iDPDAO.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<IDP> result = iDPDAO.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'IDP' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'IDP' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void IDPIntegrationTest.testFlush() {
        IDP obj = dod.getRandomIDP();
        Assert.assertNotNull("Data on demand for 'IDP' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IDP' failed to provide an identifier", id);
        obj = iDPDAO.findOne(id);
        Assert.assertNotNull("Find method for 'IDP' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyIDP(obj);
        Integer currentVersion = obj.getVersion();
        iDPDAO.flush();
        Assert.assertTrue("Version for 'IDP' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IDPIntegrationTest.testSaveUpdate() {
        IDP obj = dod.getRandomIDP();
        Assert.assertNotNull("Data on demand for 'IDP' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IDP' failed to provide an identifier", id);
        obj = iDPDAO.findOne(id);
        boolean modified =  dod.modifyIDP(obj);
        Integer currentVersion = obj.getVersion();
        IDP merged = iDPDAO.save(obj);
        iDPDAO.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'IDP' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IDPIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'IDP' failed to initialize correctly", dod.getRandomIDP());
        IDP obj = dod.getNewTransientIDP(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'IDP' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'IDP' identifier to be null", obj.getId());
        try {
            iDPDAO.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        iDPDAO.flush();
        Assert.assertNotNull("Expected 'IDP' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void IDPIntegrationTest.testDelete() {
        IDP obj = dod.getRandomIDP();
        Assert.assertNotNull("Data on demand for 'IDP' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IDP' failed to provide an identifier", id);
        obj = iDPDAO.findOne(id);
        iDPDAO.delete(obj);
        iDPDAO.flush();
        Assert.assertNull("Failed to remove 'IDP' with identifier '" + id + "'", iDPDAO.findOne(id));
    }
    
}
