// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.dao.ServiceLineDAO;
import com.capgemini.pmo.entity.ServiceLineDataOnDemand;
import com.capgemini.pmo.entity.ServiceLineIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ServiceLineIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ServiceLineIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ServiceLineIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ServiceLineIntegrationTest: @Transactional;
    
    @Autowired
    ServiceLineDataOnDemand ServiceLineIntegrationTest.dod;
    
    @Autowired
    ServiceLineDAO ServiceLineIntegrationTest.serviceLineDAO;
    
    @Test
    public void ServiceLineIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ServiceLine' failed to initialize correctly", dod.getRandomServiceLine());
        long count = serviceLineDAO.count();
        Assert.assertTrue("Counter for 'ServiceLine' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ServiceLineIntegrationTest.testFind() {
        ServiceLine obj = dod.getRandomServiceLine();
        Assert.assertNotNull("Data on demand for 'ServiceLine' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServiceLine' failed to provide an identifier", id);
        obj = serviceLineDAO.findOne(id);
        Assert.assertNotNull("Find method for 'ServiceLine' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ServiceLine' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ServiceLineIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ServiceLine' failed to initialize correctly", dod.getRandomServiceLine());
        long count = serviceLineDAO.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ServiceLine', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ServiceLine> result = serviceLineDAO.findAll();
        Assert.assertNotNull("Find all method for 'ServiceLine' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ServiceLine' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ServiceLineIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ServiceLine' failed to initialize correctly", dod.getRandomServiceLine());
        long count = serviceLineDAO.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ServiceLine> result = serviceLineDAO.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ServiceLine' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ServiceLine' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ServiceLineIntegrationTest.testFlush() {
        ServiceLine obj = dod.getRandomServiceLine();
        Assert.assertNotNull("Data on demand for 'ServiceLine' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServiceLine' failed to provide an identifier", id);
        obj = serviceLineDAO.findOne(id);
        Assert.assertNotNull("Find method for 'ServiceLine' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyServiceLine(obj);
        Integer currentVersion = obj.getVersion();
        serviceLineDAO.flush();
        Assert.assertTrue("Version for 'ServiceLine' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ServiceLineIntegrationTest.testSaveUpdate() {
        ServiceLine obj = dod.getRandomServiceLine();
        Assert.assertNotNull("Data on demand for 'ServiceLine' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServiceLine' failed to provide an identifier", id);
        obj = serviceLineDAO.findOne(id);
        boolean modified =  dod.modifyServiceLine(obj);
        Integer currentVersion = obj.getVersion();
        ServiceLine merged = serviceLineDAO.save(obj);
        serviceLineDAO.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ServiceLine' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ServiceLineIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ServiceLine' failed to initialize correctly", dod.getRandomServiceLine());
        ServiceLine obj = dod.getNewTransientServiceLine(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ServiceLine' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ServiceLine' identifier to be null", obj.getId());
        try {
            serviceLineDAO.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        serviceLineDAO.flush();
        Assert.assertNotNull("Expected 'ServiceLine' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ServiceLineIntegrationTest.testDelete() {
        ServiceLine obj = dod.getRandomServiceLine();
        Assert.assertNotNull("Data on demand for 'ServiceLine' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServiceLine' failed to provide an identifier", id);
        obj = serviceLineDAO.findOne(id);
        serviceLineDAO.delete(obj);
        serviceLineDAO.flush();
        Assert.assertNull("Failed to remove 'ServiceLine' with identifier '" + id + "'", serviceLineDAO.findOne(id));
    }
    
}
