// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.entity.ServiceLineIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ServiceLineIntegrationTest_Roo_Configurable {
    
    declare @type: ServiceLineIntegrationTest: @Configurable;
    
}
