// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.dao.ServiceLineDAO;
import com.capgemini.pmo.entity.ServiceLine;
import com.capgemini.pmo.entity.ServiceLineDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ServiceLineDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ServiceLineDataOnDemand: @Component;
    
    private Random ServiceLineDataOnDemand.rnd = new SecureRandom();
    
    private List<ServiceLine> ServiceLineDataOnDemand.data;
    
    @Autowired
    ServiceLineDAO ServiceLineDataOnDemand.serviceLineDAO;
    
    public ServiceLine ServiceLineDataOnDemand.getNewTransientServiceLine(int index) {
        ServiceLine obj = new ServiceLine();
        setName(obj, index);
        return obj;
    }
    
    public void ServiceLineDataOnDemand.setName(ServiceLine obj, int index) {
        String name = "name_" + index;
        if (name.length() > 50) {
            name = name.substring(0, 50);
        }
        obj.setName(name);
    }
    
    public ServiceLine ServiceLineDataOnDemand.getSpecificServiceLine(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ServiceLine obj = data.get(index);
        Long id = obj.getId();
        return serviceLineDAO.findOne(id);
    }
    
    public ServiceLine ServiceLineDataOnDemand.getRandomServiceLine() {
        init();
        ServiceLine obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return serviceLineDAO.findOne(id);
    }
    
    public boolean ServiceLineDataOnDemand.modifyServiceLine(ServiceLine obj) {
        return false;
    }
    
    public void ServiceLineDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = serviceLineDAO.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ServiceLine' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ServiceLine>();
        for (int i = 0; i < 10; i++) {
            ServiceLine obj = getNewTransientServiceLine(i);
            try {
                serviceLineDAO.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            serviceLineDAO.flush();
            data.add(obj);
        }
    }
    
}
