// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.dao.SkillsDAO;
import com.capgemini.pmo.entity.SkillsDataOnDemand;
import com.capgemini.pmo.entity.SkillsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SkillsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SkillsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SkillsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SkillsIntegrationTest: @Transactional;
    
    @Autowired
    SkillsDataOnDemand SkillsIntegrationTest.dod;
    
    @Autowired
    SkillsDAO SkillsIntegrationTest.skillsDAO;
    
    @Test
    public void SkillsIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Skills' failed to initialize correctly", dod.getRandomSkills());
        long count = skillsDAO.count();
        Assert.assertTrue("Counter for 'Skills' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SkillsIntegrationTest.testFind() {
        Skills obj = dod.getRandomSkills();
        Assert.assertNotNull("Data on demand for 'Skills' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Skills' failed to provide an identifier", id);
        obj = skillsDAO.findOne(id);
        Assert.assertNotNull("Find method for 'Skills' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Skills' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SkillsIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Skills' failed to initialize correctly", dod.getRandomSkills());
        long count = skillsDAO.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Skills', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Skills> result = skillsDAO.findAll();
        Assert.assertNotNull("Find all method for 'Skills' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Skills' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SkillsIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Skills' failed to initialize correctly", dod.getRandomSkills());
        long count = skillsDAO.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Skills> result = skillsDAO.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Skills' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Skills' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SkillsIntegrationTest.testFlush() {
        Skills obj = dod.getRandomSkills();
        Assert.assertNotNull("Data on demand for 'Skills' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Skills' failed to provide an identifier", id);
        obj = skillsDAO.findOne(id);
        Assert.assertNotNull("Find method for 'Skills' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySkills(obj);
        Integer currentVersion = obj.getVersion();
        skillsDAO.flush();
        Assert.assertTrue("Version for 'Skills' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SkillsIntegrationTest.testSaveUpdate() {
        Skills obj = dod.getRandomSkills();
        Assert.assertNotNull("Data on demand for 'Skills' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Skills' failed to provide an identifier", id);
        obj = skillsDAO.findOne(id);
        boolean modified =  dod.modifySkills(obj);
        Integer currentVersion = obj.getVersion();
        Skills merged = skillsDAO.save(obj);
        skillsDAO.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Skills' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SkillsIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Skills' failed to initialize correctly", dod.getRandomSkills());
        Skills obj = dod.getNewTransientSkills(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Skills' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Skills' identifier to be null", obj.getId());
        try {
            skillsDAO.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        skillsDAO.flush();
        Assert.assertNotNull("Expected 'Skills' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SkillsIntegrationTest.testDelete() {
        Skills obj = dod.getRandomSkills();
        Assert.assertNotNull("Data on demand for 'Skills' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Skills' failed to provide an identifier", id);
        obj = skillsDAO.findOne(id);
        skillsDAO.delete(obj);
        skillsDAO.flush();
        Assert.assertNull("Failed to remove 'Skills' with identifier '" + id + "'", skillsDAO.findOne(id));
    }
    
}
