// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.entity.Account;
import com.capgemini.pmo.entity.IDP;

privileged aspect Account_Roo_JavaBean {
    
    public String Account.getName() {
        return this.name;
    }
    
    public void Account.setName(String name) {
        this.name = name;
    }
    
    public IDP Account.getIdp() {
        return this.idp;
    }
    
    public void Account.setIdp(IDP idp) {
        this.idp = idp;
    }
    
    public String Account.getAccountexec() {
        return this.accountexec;
    }
    
    public void Account.setAccountexec(String accountexec) {
        this.accountexec = accountexec;
    }
    
    public String Account.getPmocontact() {
        return this.pmocontact;
    }
    
    public void Account.setPmocontact(String pmocontact) {
        this.pmocontact = pmocontact;
    }
    
    public Integer Account.getHeadcount() {
        return this.headcount;
    }
    
    public void Account.setHeadcount(Integer headcount) {
        this.headcount = headcount;
    }
    
}
