// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.entity.AppsServiceLine;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect AppsServiceLine_Roo_Jpa_Entity {
    
    declare @type: AppsServiceLine: @Entity;
    
    declare @type: AppsServiceLine: @Table(name = "T_IDP_SERVICE_LINE");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long AppsServiceLine.id;
    
    @Version
    @Column(name = "version")
    private Integer AppsServiceLine.version;
    
    public Long AppsServiceLine.getId() {
        return this.id;
    }
    
    public void AppsServiceLine.setId(Long id) {
        this.id = id;
    }
    
    public Integer AppsServiceLine.getVersion() {
        return this.version;
    }
    
    public void AppsServiceLine.setVersion(Integer version) {
        this.version = version;
    }
    
}
