// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.constant.ActiveInactiveFlag;
import com.capgemini.pmo.entity.AppsServiceLine;
import com.capgemini.pmo.entity.IDP;
import com.capgemini.pmo.entity.ServiceLine;
import com.capgemini.pmo.entity.Skills;
import java.util.Set;

privileged aspect AppsServiceLine_Roo_JavaBean {
    
    public IDP AppsServiceLine.getIdp() {
        return this.idp;
    }
    
    public void AppsServiceLine.setIdp(IDP idp) {
        this.idp = idp;
    }
    
    public ServiceLine AppsServiceLine.getServiceline() {
        return this.serviceline;
    }
    
    public void AppsServiceLine.setServiceline(ServiceLine serviceline) {
        this.serviceline = serviceline;
    }
    
    public ActiveInactiveFlag AppsServiceLine.getActive() {
        return this.Active;
    }
    
    public void AppsServiceLine.setActive(ActiveInactiveFlag Active) {
        this.Active = Active;
    }
    
    public Set<Skills> AppsServiceLine.getSkills() {
        return this.skills;
    }
    
    public void AppsServiceLine.setSkills(Set<Skills> skills) {
        this.skills = skills;
    }
    
}
