// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.entity.BuisnessUnit;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect BuisnessUnit_Roo_Jpa_Entity {
    
    declare @type: BuisnessUnit: @Entity;
    
    declare @type: BuisnessUnit: @Table(name = "T_BUISNESS_UNIT");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long BuisnessUnit.id;
    
    @Version
    @Column(name = "version")
    private Integer BuisnessUnit.version;
    
    public Long BuisnessUnit.getId() {
        return this.id;
    }
    
    public void BuisnessUnit.setId(Long id) {
        this.id = id;
    }
    
    public Integer BuisnessUnit.getVersion() {
        return this.version;
    }
    
    public void BuisnessUnit.setVersion(Integer version) {
        this.version = version;
    }
    
}
