// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.constant.AccountStatus;
import com.capgemini.pmo.constant.EmpBillability;
import com.capgemini.pmo.entity.EmployeeMaster;
import com.capgemini.pmo.entity.EmployeeRoster;
import com.capgemini.pmo.entity.Project;
import java.util.Calendar;

privileged aspect EmployeeRoster_Roo_JavaBean {
    
    public EmployeeMaster EmployeeRoster.getEmp() {
        return this.emp;
    }
    
    public void EmployeeRoster.setEmp(EmployeeMaster emp) {
        this.emp = emp;
    }
    
    public Project EmployeeRoster.getProjectcode() {
        return this.projectcode;
    }
    
    public void EmployeeRoster.setProjectcode(Project projectcode) {
        this.projectcode = projectcode;
    }
    
    public Calendar EmployeeRoster.getTaggingstartdate() {
        return this.taggingstartdate;
    }
    
    public void EmployeeRoster.setTaggingstartdate(Calendar taggingstartdate) {
        this.taggingstartdate = taggingstartdate;
    }
    
    public Calendar EmployeeRoster.getTaggingenddate() {
        return this.taggingenddate;
    }
    
    public void EmployeeRoster.setTaggingenddate(Calendar taggingenddate) {
        this.taggingenddate = taggingenddate;
    }
    
    public EmpBillability EmployeeRoster.getBillability() {
        return this.billability;
    }
    
    public void EmployeeRoster.setBillability(EmpBillability billability) {
        this.billability = billability;
    }
    
    public AccountStatus EmployeeRoster.getAccountstatus() {
        return this.accountstatus;
    }
    
    public void EmployeeRoster.setAccountstatus(AccountStatus accountstatus) {
        this.accountstatus = accountstatus;
    }
    
    public String EmployeeRoster.getPmocomments() {
        return this.pmocomments;
    }
    
    public void EmployeeRoster.setPmocomments(String pmocomments) {
        this.pmocomments = pmocomments;
    }
    
    public Calendar EmployeeRoster.getRolloffdate() {
        return this.rolloffdate;
    }
    
    public void EmployeeRoster.setRolloffdate(Calendar rolloffdate) {
        this.rolloffdate = rolloffdate;
    }
    
    public String EmployeeRoster.getRolloffreason() {
        return this.rolloffreason;
    }
    
    public void EmployeeRoster.setRolloffreason(String rolloffreason) {
        this.rolloffreason = rolloffreason;
    }
    
    public String EmployeeRoster.getSource() {
        return this.source;
    }
    
    public void EmployeeRoster.setSource(String source) {
        this.source = source;
    }
    
    public Calendar EmployeeRoster.getAccntstartdate() {
        return this.accntstartdate;
    }
    
    public void EmployeeRoster.setAccntstartdate(Calendar accntstartdate) {
        this.accntstartdate = accntstartdate;
    }
    
    public Integer EmployeeRoster.getAvailability() {
        return this.availability;
    }
    
    public void EmployeeRoster.setAvailability(Integer availability) {
        this.availability = availability;
    }
    
}
