// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.entity.EmployeeMaster;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect EmployeeMaster_Roo_Jpa_Entity {
    
    declare @type: EmployeeMaster: @Entity;
    
    declare @type: EmployeeMaster: @Table(name = "T_EMPLOYEE");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long EmployeeMaster.id;
    
    @Version
    @Column(name = "version")
    private Integer EmployeeMaster.version;
    
    public Long EmployeeMaster.getId() {
        return this.id;
    }
    
    public void EmployeeMaster.setId(Long id) {
        this.id = id;
    }
    
    public Integer EmployeeMaster.getVersion() {
        return this.version;
    }
    
    public void EmployeeMaster.setVersion(Integer version) {
        this.version = version;
    }
    
}
