// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.constant.ActiveInactiveFlag;
import com.capgemini.pmo.entity.BuisnessUnit;
import com.capgemini.pmo.entity.IDP;

privileged aspect IDP_Roo_JavaBean {
    
    public String IDP.getName() {
        return this.name;
    }
    
    public void IDP.setName(String name) {
        this.name = name;
    }
    
    public String IDP.getIdphead() {
        return this.idphead;
    }
    
    public void IDP.setIdphead(String idphead) {
        this.idphead = idphead;
    }
    
    public BuisnessUnit IDP.getBuorg() {
        return this.buorg;
    }
    
    public void IDP.setBuorg(BuisnessUnit buorg) {
        this.buorg = buorg;
    }
    
    public ActiveInactiveFlag IDP.getActiveFlag() {
        return this.ActiveFlag;
    }
    
    public void IDP.setActiveFlag(ActiveInactiveFlag ActiveFlag) {
        this.ActiveFlag = ActiveFlag;
    }
    
}
