// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.constant.Currency;
import com.capgemini.pmo.entity.Account;
import com.capgemini.pmo.entity.IDP;
import com.capgemini.pmo.entity.Project;
import java.math.BigDecimal;
import java.util.Calendar;

privileged aspect Project_Roo_JavaBean {
    
    public IDP Project.getIdpname() {
        return this.idpname;
    }
    
    public void Project.setIdpname(IDP idpname) {
        this.idpname = idpname;
    }
    
    public Account Project.getAccount() {
        return this.account;
    }
    
    public void Project.setAccount(Account account) {
        this.account = account;
    }
    
    public String Project.getProjectCode() {
        return this.projectCode;
    }
    
    public void Project.setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }
    
    public String Project.getProjectName() {
        return this.projectName;
    }
    
    public void Project.setProjectName(String projectName) {
        this.projectName = projectName;
    }
    
    public String Project.getDescription() {
        return this.description;
    }
    
    public void Project.setDescription(String description) {
        this.description = description;
    }
    
    public Calendar Project.getStartdate() {
        return this.startdate;
    }
    
    public void Project.setStartdate(Calendar startdate) {
        this.startdate = startdate;
    }
    
    public Calendar Project.getEnddate() {
        return this.enddate;
    }
    
    public void Project.setEnddate(Calendar enddate) {
        this.enddate = enddate;
    }
    
    public BigDecimal Project.getBudcm() {
        return this.budcm;
    }
    
    public void Project.setBudcm(BigDecimal budcm) {
        this.budcm = budcm;
    }
    
    public BigDecimal Project.getBudpyrd() {
        return this.budpyrd;
    }
    
    public void Project.setBudpyrd(BigDecimal budpyrd) {
        this.budpyrd = budpyrd;
    }
    
    public BigDecimal Project.getBudheadcount() {
        return this.budheadcount;
    }
    
    public void Project.setBudheadcount(BigDecimal budheadcount) {
        this.budheadcount = budheadcount;
    }
    
    public BigDecimal Project.getRevenue() {
        return this.revenue;
    }
    
    public void Project.setRevenue(BigDecimal revenue) {
        this.revenue = revenue;
    }
    
    public String Project.getEngagmanager() {
        return this.engagmanager;
    }
    
    public void Project.setEngagmanager(String engagmanager) {
        this.engagmanager = engagmanager;
    }
    
    public String Project.getProjmanager() {
        return this.projmanager;
    }
    
    public void Project.setProjmanager(String projmanager) {
        this.projmanager = projmanager;
    }
    
    public Currency Project.getCurrency() {
        return this.currency;
    }
    
    public void Project.setCurrency(Currency currency) {
        this.currency = currency;
    }
    
}
