// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.entity.ServiceLine;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect ServiceLine_Roo_Jpa_Entity {
    
    declare @type: ServiceLine: @Entity;
    
    declare @type: ServiceLine: @Table(name = "T_SERVICE_LINE");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long ServiceLine.id;
    
    @Version
    @Column(name = "version")
    private Integer ServiceLine.version;
    
    public Long ServiceLine.getId() {
        return this.id;
    }
    
    public void ServiceLine.setId(Long id) {
        this.id = id;
    }
    
    public Integer ServiceLine.getVersion() {
        return this.version;
    }
    
    public void ServiceLine.setVersion(Integer version) {
        this.version = version;
    }
    
}
