// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.entity.ServiceLine;

privileged aspect ServiceLine_Roo_JavaBean {
    
    public String ServiceLine.getName() {
        return this.name;
    }
    
    public void ServiceLine.setName(String name) {
        this.name = name;
    }
    
}
