// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.entity.Skills;

privileged aspect Skills_Roo_JavaBean {
    
    public String Skills.getSkillname() {
        return this.skillname;
    }
    
    public void Skills.setSkillname(String skillname) {
        this.skillname = skillname;
    }
    
}
