// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.entity;

import com.capgemini.pmo.entity.Skills;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect Skills_Roo_Jpa_Entity {
    
    declare @type: Skills: @Entity;
    
    declare @type: Skills: @Table(name = "T_SKILL");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Skills.id;
    
    @Version
    @Column(name = "version")
    private Integer Skills.version;
    
    public Long Skills.getId() {
        return this.id;
    }
    
    public void Skills.setId(Long id) {
        this.id = id;
    }
    
    public Integer Skills.getVersion() {
        return this.version;
    }
    
    public void Skills.setVersion(Integer version) {
        this.version = version;
    }
    
}
