// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.dao;

import com.capgemini.pmo.dao.AccountDAO;
import com.capgemini.pmo.entity.Account;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect AccountDAO_Roo_Jpa_Repository {
    
    declare parents: AccountDAO extends JpaRepository<Account, Long>;
    
    declare parents: AccountDAO extends JpaSpecificationExecutor<Account>;
    
    declare @type: AccountDAO: @Repository;
    
}
