// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.dao;

import com.capgemini.pmo.dao.EmployeeMasterDAO;
import com.capgemini.pmo.entity.EmployeeMaster;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect EmployeeMasterDAO_Roo_Jpa_Repository {
    
    declare parents: EmployeeMasterDAO extends JpaRepository<EmployeeMaster, Long>;
    
    declare parents: EmployeeMasterDAO extends JpaSpecificationExecutor<EmployeeMaster>;
    
    declare @type: EmployeeMasterDAO: @Repository;
    
}
