// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.dao;

import com.capgemini.pmo.dao.EmployeeRosterDAO;
import com.capgemini.pmo.entity.EmployeeRoster;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect EmployeeRosterDAO_Roo_Jpa_Repository {
    
    declare parents: EmployeeRosterDAO extends JpaRepository<EmployeeRoster, Long>;
    
    declare parents: EmployeeRosterDAO extends JpaSpecificationExecutor<EmployeeRoster>;
    
    declare @type: EmployeeRosterDAO: @Repository;
    
}
