// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.dao;

import com.capgemini.pmo.dao.ProjectDAO;
import com.capgemini.pmo.entity.Project;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect ProjectDAO_Roo_Jpa_Repository {
    
    declare parents: ProjectDAO extends JpaRepository<Project, Long>;
    
    declare parents: ProjectDAO extends JpaSpecificationExecutor<Project>;
    
    declare @type: ProjectDAO: @Repository;
    
}
