// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.dao;

import com.capgemini.pmo.dao.SkillsDAO;
import com.capgemini.pmo.entity.Skills;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect SkillsDAO_Roo_Jpa_Repository {
    
    declare parents: SkillsDAO extends JpaRepository<Skills, Long>;
    
    declare parents: SkillsDAO extends JpaSpecificationExecutor<Skills>;
    
    declare @type: SkillsDAO: @Repository;
    
}
