// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.controller;

import com.capgemini.pmo.constant.ActiveInactiveFlag;
import com.capgemini.pmo.controller.BUController;
import com.capgemini.pmo.dao.BUDAO;
import com.capgemini.pmo.entity.BuisnessUnit;
import java.io.UnsupportedEncodingException;
import java.util.Arrays;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect BUController_Roo_Controller {
    
    @Autowired
    BUDAO BUController.bUDAO;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String BUController.create(@Valid BuisnessUnit buisnessUnit, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, buisnessUnit);
            return "buisnessunits/create";
        }
        uiModel.asMap().clear();
        bUDAO.save(buisnessUnit);
        return "redirect:/buisnessunits/" + encodeUrlPathSegment(buisnessUnit.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String BUController.createForm(Model uiModel) {
        populateEditForm(uiModel, new BuisnessUnit());
        return "buisnessunits/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String BUController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("buisnessunit", bUDAO.findOne(id));
        uiModel.addAttribute("itemId", id);
        return "buisnessunits/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String BUController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("buisnessunits", bUDAO.findAll(new org.springframework.data.domain.PageRequest(firstResult / sizeNo, sizeNo)).getContent());
            float nrOfPages = (float) bUDAO.count() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("buisnessunits", bUDAO.findAll());
        }
        return "buisnessunits/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String BUController.update(@Valid BuisnessUnit buisnessUnit, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, buisnessUnit);
            return "buisnessunits/update";
        }
        uiModel.asMap().clear();
        bUDAO.save(buisnessUnit);
        return "redirect:/buisnessunits/" + encodeUrlPathSegment(buisnessUnit.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String BUController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, bUDAO.findOne(id));
        return "buisnessunits/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String BUController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        BuisnessUnit buisnessUnit = bUDAO.findOne(id);
        bUDAO.delete(buisnessUnit);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/buisnessunits";
    }
    
    void BUController.populateEditForm(Model uiModel, BuisnessUnit buisnessUnit) {
        uiModel.addAttribute("buisnessUnit", buisnessUnit);
        uiModel.addAttribute("activeinactiveflags", Arrays.asList(ActiveInactiveFlag.values()));
    }
    
    String BUController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
