// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.controller;

import com.capgemini.pmo.constant.ActiveInactiveFlag;
import com.capgemini.pmo.controller.IDPController;
import com.capgemini.pmo.dao.BUDAO;
import com.capgemini.pmo.dao.IDPDAO;
import com.capgemini.pmo.entity.BuisnessUnit;
import com.capgemini.pmo.entity.IDP;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect IDPController_Roo_Controller {
    
    @Autowired
    BUDAO IDPController.bUDAO;
    
    @Autowired
    IDPDAO IDPController.iDPDAO;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String IDPController.create(@Valid IDP IDP_, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, IDP_);
            return "idps/create";
        }
        uiModel.asMap().clear();
        iDPDAO.save(IDP_);
        return "redirect:/idps/" + encodeUrlPathSegment(IDP_.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String IDPController.createForm(Model uiModel) {
        populateEditForm(uiModel, new IDP());
        List<String[]> dependencies = new ArrayList<String[]>();
        if (bUDAO.count() == 0) {
            dependencies.add(new String[] { "buorg", "buisnessunits" });
        }
        uiModel.addAttribute("dependencies", dependencies);
        return "idps/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String IDPController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("idp_", iDPDAO.findOne(id));
        uiModel.addAttribute("itemId", id);
        return "idps/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String IDPController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("idps", iDPDAO.findAll(new org.springframework.data.domain.PageRequest(firstResult / sizeNo, sizeNo)).getContent());
            float nrOfPages = (float) iDPDAO.count() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("idps", iDPDAO.findAll());
        }
        return "idps/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String IDPController.update(@Valid IDP IDP_, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, IDP_);
            return "idps/update";
        }
        uiModel.asMap().clear();
        iDPDAO.save(IDP_);
        return "redirect:/idps/" + encodeUrlPathSegment(IDP_.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String IDPController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, iDPDAO.findOne(id));
        return "idps/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String IDPController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        IDP IDP_ = iDPDAO.findOne(id);
        iDPDAO.delete(IDP_);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/idps";
    }
    
    void IDPController.populateEditForm(Model uiModel, IDP IDP_) {
        uiModel.addAttribute("IDP_", IDP_);
        uiModel.addAttribute("activeinactiveflags", Arrays.asList(ActiveInactiveFlag.values()));
        uiModel.addAttribute("buisnessunits", bUDAO.findAll());
    }
    
    String IDPController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
