// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.controller;

import com.capgemini.pmo.controller.ServiceLineController;
import com.capgemini.pmo.dao.ServiceLineDAO;
import com.capgemini.pmo.entity.ServiceLine;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect ServiceLineController_Roo_Controller {
    
    @Autowired
    ServiceLineDAO ServiceLineController.serviceLineDAO;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ServiceLineController.create(@Valid ServiceLine serviceLine, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, serviceLine);
            return "servicelines/create";
        }
        uiModel.asMap().clear();
        serviceLineDAO.save(serviceLine);
        return "redirect:/servicelines/" + encodeUrlPathSegment(serviceLine.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ServiceLineController.createForm(Model uiModel) {
        populateEditForm(uiModel, new ServiceLine());
        return "servicelines/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ServiceLineController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("serviceline", serviceLineDAO.findOne(id));
        uiModel.addAttribute("itemId", id);
        return "servicelines/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ServiceLineController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("servicelines", serviceLineDAO.findAll(new org.springframework.data.domain.PageRequest(firstResult / sizeNo, sizeNo)).getContent());
            float nrOfPages = (float) serviceLineDAO.count() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("servicelines", serviceLineDAO.findAll());
        }
        return "servicelines/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ServiceLineController.update(@Valid ServiceLine serviceLine, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, serviceLine);
            return "servicelines/update";
        }
        uiModel.asMap().clear();
        serviceLineDAO.save(serviceLine);
        return "redirect:/servicelines/" + encodeUrlPathSegment(serviceLine.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ServiceLineController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, serviceLineDAO.findOne(id));
        return "servicelines/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ServiceLineController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ServiceLine serviceLine = serviceLineDAO.findOne(id);
        serviceLineDAO.delete(serviceLine);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/servicelines";
    }
    
    void ServiceLineController.populateEditForm(Model uiModel, ServiceLine serviceLine) {
        uiModel.addAttribute("serviceLine", serviceLine);
    }
    
    String ServiceLineController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
