// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.capgemini.pmo.controller;

import com.capgemini.pmo.controller.SkillsController;
import com.capgemini.pmo.dao.SkillsDAO;
import com.capgemini.pmo.entity.Skills;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect SkillsController_Roo_Controller {
    
    @Autowired
    SkillsDAO SkillsController.skillsDAO;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String SkillsController.create(@Valid Skills skills, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, skills);
            return "skillses/create";
        }
        uiModel.asMap().clear();
        skillsDAO.save(skills);
        return "redirect:/skillses/" + encodeUrlPathSegment(skills.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String SkillsController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Skills());
        return "skillses/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String SkillsController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("skills", skillsDAO.findOne(id));
        uiModel.addAttribute("itemId", id);
        return "skillses/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String SkillsController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("skillses", skillsDAO.findAll(new org.springframework.data.domain.PageRequest(firstResult / sizeNo, sizeNo)).getContent());
            float nrOfPages = (float) skillsDAO.count() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("skillses", skillsDAO.findAll());
        }
        return "skillses/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String SkillsController.update(@Valid Skills skills, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, skills);
            return "skillses/update";
        }
        uiModel.asMap().clear();
        skillsDAO.save(skills);
        return "redirect:/skillses/" + encodeUrlPathSegment(skills.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String SkillsController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, skillsDAO.findOne(id));
        return "skillses/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String SkillsController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Skills skills = skillsDAO.findOne(id);
        skillsDAO.delete(skills);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/skillses";
    }
    
    void SkillsController.populateEditForm(Model uiModel, Skills skills) {
        uiModel.addAttribute("skills", skills);
    }
    
    String SkillsController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
